/**
 * Zeus Skill Pool (20 skills)
 * Types:
 * - "chain": chain lightning between enemies
 * - "aoe": ground-targeted circular AOE
 * - "aura": toggle aura around player (ticks damage, costs mana per tick)
 * - "storm": random strikes in radius over duration
 * - "beam": instant single-target zap to nearest enemy in range
 * - "nova": instant radial burst around player
 *
 * Each skill provides only the params relevant to its type.
 * All numbers are tuned near the original Q/W/E/R for parity.
 */
export const SKILL_POOL = [
  {
    id: "chain_lightning",
    name: "Chain Lightning",
    short: "Chain",
    type: "chain",
    cd: 5,
    mana: 22,
    range: 45,
    jumps: 5,
    jumpRange: 24,
    dmg: 24,
  },
  {
    id: "lightning_bolt",
    name: "Lightning Bolt",
    short: "Bolt",
    type: "aoe",
    cd: 8,
    mana: 34,
    radius: 16,
    dmg: 35,
    slowFactor: 0.45,
    slowDuration: 1.5,
  },
  {
    id: "static_field",
    name: "Static Field",
    short: "Static",
    type: "aura",
    cd: 15,
    mana: 0,
    radius: 14,
    tick: 0.7,
    dmg: 8,
    duration: 10,
    manaPerTick: 2,
  },
  {
    id: "thunderstorm",
    name: "Thunderstorm",
    short: "Storm",
    type: "storm",
    cd: 22,
    mana: 55,
    radius: 30,
    strikes: 22,
    dmg: 20,
    duration: 7,
  },
  // Additional skills (variants)
  {
    id: "zeus_bolt",
    name: "Zeus Bolt",
    short: "Bolt+",
    type: "beam",
    cd: 2.5,
    mana: 14,
    range: 36,
    dmg: 22,
  },
  {
    id: "ion_nova",
    name: "Ion Nova",
    short: "Nova",
    type: "nova",
    cd: 12,
    mana: 26,
    radius: 14,
    dmg: 30,
  },
  {
    id: "overcharge_aura",
    name: "Overcharge Aura",
    short: "O-Chg",
    type: "aura",
    cd: 18,
    mana: 0,
    radius: 12,
    tick: 0.5,
    dmg: 6,
    duration: 9,
    manaPerTick: 2.5,
  },
  {
    id: "ball_lightning",
    name: "Ball Lightning",
    short: "Ball",
    type: "beam",
    cd: 2.2,
    mana: 16,
    range: 48,
    dmg: 20,
  },
  {
    id: "arc_spear",
    name: "Arc Spear",
    short: "Spear",
    type: "beam",
    cd: 3.2,
    mana: 18,
    range: 52,
    dmg: 28,
  },
  {
    id: "sky_wrath",
    name: "Sky Wrath",
    short: "Wrath",
    type: "storm",
    cd: 18,
    mana: 42,
    radius: 24,
    strikes: 14,
    dmg: 18,
    duration: 5.5,
  },
  {
    id: "tempest_ring",
    name: "Tempest Ring",
    short: "Ring",
    type: "aoe",
    cd: 10,
    mana: 32,
    radius: 18,
    dmg: 32,
    slowFactor: 0.4,
    slowDuration: 1.2,
  },
  {
    id: "storm_pulse",
    name: "Storm Pulse",
    short: "Pulse",
    type: "nova",
    cd: 9,
    mana: 22,
    radius: 12,
    dmg: 24,
  },
  {
    id: "crackling_field",
    name: "Crackling Field",
    short: "C-Field",
    type: "aura",
    cd: 14,
    mana: 0,
    radius: 13,
    tick: 0.6,
    dmg: 7,
    duration: 8,
    manaPerTick: 2,
  },
  {
    id: "thundersurge",
    name: "Thundersurge",
    short: "Surge",
    type: "chain",
    cd: 6,
    mana: 26,
    range: 42,
    jumps: 4,
    jumpRange: 22,
    dmg: 28,
  },
  {
    id: "forked_lightning",
    name: "Forked Lightning",
    short: "Fork",
    type: "chain",
    cd: 7,
    mana: 24,
    range: 40,
    jumps: 6,
    jumpRange: 20,
    dmg: 20,
  },
  {
    id: "thunderdome",
    name: "Thunderdome",
    short: "Dome",
    type: "storm",
    cd: 24,
    mana: 60,
    radius: 32,
    strikes: 28,
    dmg: 18,
    duration: 8,
  },
  {
    id: "shockwave",
    name: "Shockwave",
    short: "Shock",
    type: "beam",
    cd: 2.8,
    mana: 15,
    range: 40,
    dmg: 24,
  },
  {
    id: "magneto_burst",
    name: "Magneto Burst",
    short: "Burst",
    type: "aoe",
    cd: 11,
    mana: 36,
    radius: 17,
    dmg: 34,
    slowFactor: 0.5,
    slowDuration: 1.3,
  },
  {
    id: "ion_storm",
    name: "Ion Storm",
    short: "Ion",
    type: "storm",
    cd: 20,
    mana: 50,
    radius: 28,
    strikes: 20,
    dmg: 19,
    duration: 6.5,
  },
  {
    id: "static_overload",
    name: "Static Overload",
    short: "Over",
    type: "aura",
    cd: 16,
    mana: 0,
    radius: 15,
    tick: 0.55,
    dmg: 9,
    duration: 9,
    manaPerTick: 3,
  },
];

/**
 * Default loadout mapping to original Q/W/E/R equivalents.
 */
export const DEFAULT_LOADOUT = ["chain_lightning", "lightning_bolt", "static_field", "thunderstorm"];
