/**
 * Zeus Skill Pool — Enhanced with per-skill VFX "effects" and diversified roles
 *
 * effects:
 *  - beam: beam/electric color (hex)
 *  - impact: strike/decal color (hex)
 *  - ring: ground ring color (hex)
 *  - arc: secondary arc color (hex)
 *  - hand: hand flash tint (hex)
 *  - shake: camera shake magnitude (0..1)
 */
export const SKILL_POOL = [
  // Core lightning kit — refined
  {
    id: "chain_lightning",
    name: "Chain Lightning",
    short: "Chain",
    type: "chain",
    cd: 5,
    mana: 22,
    range: 45,
    jumps: 5,
    jumpRange: 24,
    dmg: 24,
    slowFactor: 0.25,
    slowDuration: 0.9,
    effects: { beam: 0xdff3ff, arc: 0xbfe9ff, impact: 0x9fd8ff, ring: 0x7fc7ff, hand: 0x9fd8ff, shake: 0.2 },
  },
  {
    id: "lightning_bolt",
    name: "Lightning Bolt",
    short: "Bolt",
    type: "aoe",
    cd: 8,
    mana: 34,
    radius: 16,
    dmg: 35,
    slowFactor: 0.45,
    slowDuration: 1.5,
    effects: { ring: 0xffa54d, impact: 0xffd86a, arc: 0xffbb66, hand: 0xffd86a, shake: 0.35 },
  },
  {
    id: "static_field",
    name: "Static Field",
    short: "Static",
    type: "aura",
    cd: 15,
    mana: 0,
    radius: 14,
    tick: 0.7,
    dmg: 8,
    duration: 10,
    manaPerTick: 2,
    effects: { ring: 0x7fc7ff, impact: 0x7fc7ff, hand: 0x9fd8ff, shake: 0.1 },
  },
  {
    id: "thunderstorm",
    name: "Thunderstorm",
    short: "Storm",
    type: "storm",
    cd: 22,
    mana: 55,
    radius: 30,
    strikes: 22,
    dmg: 20,
    duration: 7,
    effects: { impact: 0xb5e2ff, ring: 0x88ccff, hand: 0x9fd8ff, shake: 0.45 },
  },

  // Beams / Novas
  {
    id: "zeus_bolt",
    name: "Zeus Bolt",
    short: "Bolt+",
    type: "beam",
    cd: 2.5,
    mana: 14,
    range: 36,
    dmg: 22,
    effects: { beam: 0xdff6ff, impact: 0xdeeaff, hand: 0xdff3ff, shake: 0.2 },
  },
  {
    id: "ion_nova",
    name: "Ion Nova",
    short: "Nova",
    type: "nova",
    cd: 12,
    mana: 26,
    radius: 14,
    dmg: 30,
    effects: { ring: 0x66ffe0, impact: 0x99ffee, hand: 0x66ffe0, shake: 0.35 },
  },

  // Auras (variants)
  {
    id: "overcharge_aura",
    name: "Overcharge Aura",
    short: "O-Chg",
    type: "aura",
    cd: 18,
    mana: 0,
    radius: 12,
    tick: 0.5,
    dmg: 6,
    duration: 9,
    manaPerTick: 2.5,
    effects: { ring: 0xffef85, impact: 0xffd86a, hand: 0xffd86a, shake: 0.18 },
  },
  {
    id: "crackling_field",
    name: "Crackling Field",
    short: "C-Field",
    type: "aura",
    cd: 14,
    mana: 0,
    radius: 13,
    tick: 0.6,
    dmg: 7,
    duration: 8,
    manaPerTick: 2,
    effects: { ring: 0x9fd8ff, impact: 0x9fd8ff, hand: 0x9fd8ff, shake: 0.15 },
  },
  {
    id: "static_overload",
    name: "Static Overload",
    short: "Over",
    type: "aura",
    cd: 16,
    mana: 0,
    radius: 15,
    tick: 0.55,
    dmg: 9,
    duration: 9,
    manaPerTick: 3,
    effects: { ring: 0xbfe9ff, impact: 0x7fc7ff, hand: 0xbfe9ff, shake: 0.2 },
  },

  // Beams and tools
  {
    id: "ball_lightning",
    name: "Ball Lightning",
    short: "Ball",
    type: "beam",
    cd: 2.2,
    mana: 16,
    range: 48,
    dmg: 20,
    effects: { beam: 0x88ccff, impact: 0xa0ddff, hand: 0x88ccff, shake: 0.22 },
  },
  {
    id: "arc_spear",
    name: "Arc Spear",
    short: "Spear",
    type: "beam",
    cd: 3.2,
    mana: 18,
    range: 52,
    dmg: 28,
    effects: { beam: 0xff88e6, impact: 0xffa5ee, hand: 0xff88e6, shake: 0.28 },
  },
  {
    id: "shockwave",
    name: "Shockwave",
    short: "Shock",
    type: "beam",
    cd: 2.8,
    mana: 15,
    range: 40,
    dmg: 24,
    effects: { beam: 0xff6050, impact: 0xff8a7a, hand: 0xff7563, shake: 0.3 },
  },

  // Storm variants
  {
    id: "sky_wrath",
    name: "Sky Wrath",
    short: "Wrath",
    type: "storm",
    cd: 18,
    mana: 42,
    radius: 24,
    strikes: 14,
    dmg: 18,
    duration: 5.5,
    effects: { impact: 0xcc99ff, ring: 0xa97bff, hand: 0xbf8cff, shake: 0.35 },
  },
  {
    id: "thunderdome",
    name: "Thunderdome",
    short: "Dome",
    type: "storm",
    cd: 24,
    mana: 60,
    radius: 32,
    strikes: 28,
    dmg: 18,
    duration: 8,
    effects: { impact: 0x88bbff, ring: 0x66aaff, hand: 0x88bbff, shake: 0.6 },
  },
  {
    id: "ion_storm",
    name: "Ion Storm",
    short: "Ion",
    type: "storm",
    cd: 20,
    mana: 50,
    radius: 28,
    strikes: 20,
    dmg: 19,
    duration: 6.5,
    effects: { impact: 0x88ffee, ring: 0x66ffe0, hand: 0x66ffe0, shake: 0.38 },
  },

  // AOEs — control and burst
  {
    id: "tempest_ring",
    name: "Tempest Ring",
    short: "Ring",
    type: "aoe",
    cd: 10,
    mana: 32,
    radius: 18,
    dmg: 32,
    slowFactor: 0.4,
    slowDuration: 1.2,
    effects: { ring: 0x7dd3ff, impact: 0x9bdfff, hand: 0x9fd8ff, shake: 0.32 },
  },
  {
    id: "storm_pulse",
    name: "Storm Pulse",
    short: "Pulse",
    type: "nova",
    cd: 9,
    mana: 22,
    radius: 12,
    dmg: 24,
    effects: { ring: 0x88ccff, impact: 0xa0ddff, hand: 0x88ccff, shake: 0.26 },
  },
  {
    id: "magneto_burst",
    name: "Magneto Burst",
    short: "Burst",
    type: "aoe",
    cd: 11,
    mana: 36,
    radius: 17,
    dmg: 34,
    slowFactor: 0.5,
    slowDuration: 1.3,
    effects: { ring: 0xff6a6a, impact: 0xff9494, hand: 0xff7a7a, shake: 0.4 },
  },
  {
    id: "static_prison",
    name: "Static Prison",
    short: "Prison",
    type: "aoe",
    cd: 16,
    mana: 38,
    radius: 14,
    dmg: 18,
    slowFactor: 0.7,
    slowDuration: 2.8,
    effects: { ring: 0xc080ff, impact: 0xe0a0ff, hand: 0xc080ff, shake: 0.36 },
  },

  // Chains — variants and control
  {
    id: "thundersurge",
    name: "Thundersurge",
    short: "Surge",
    type: "chain",
    cd: 6,
    mana: 26,
    range: 42,
    jumps: 4,
    jumpRange: 22,
    dmg: 28,
    slowFactor: 0.2,
    slowDuration: 1.0,
    effects: { beam: 0xcfefff, arc: 0xbfe9ff, impact: 0xa8e0ff, ring: 0x8fd3ff, hand: 0xa8e0ff, shake: 0.24 },
  },
  {
    id: "forked_lightning",
    name: "Forked Lightning",
    short: "Fork",
    type: "chain",
    cd: 7,
    mana: 24,
    range: 40,
    jumps: 6,
    jumpRange: 20,
    dmg: 20,
    slowFactor: 0.15,
    slowDuration: 1.2,
    effects: { beam: 0x88e0ff, arc: 0xa0eaff, impact: 0x88ccff, ring: 0x7fc7ff, hand: 0x88ccff, shake: 0.22 },
  },

  // Sustain / Utility
  {
    id: "thunder_mend",
    name: "Thunder Mend",
    short: "Heal",
    type: "heal",
    cd: 14,
    mana: 24,
    heal: 55,
    effects: { impact: 0x85ffb2, ring: 0x66ff99, hand: 0x85ffc1, shake: 0.18 },
  },
  {
    id: "divine_mend",
    name: "Divine Mend",
    short: "Mend+",
    type: "heal",
    cd: 30,
    mana: 40,
    heal: 160,
    effects: { impact: 0x66ff99, ring: 0x55ff88, hand: 0x88ffd0, shake: 0.25 },
  },
  {
    id: "storm_sip",
    name: "Storm Sip",
    short: "Mana",
    type: "mana",
    cd: 12,
    mana: 0,
    restore: 40,
    effects: { impact: 0x88aaff, ring: 0x99bbff, hand: 0x88ccff, shake: 0.1 },
  },
  {
    id: "mana_well",
    name: "Mana Well",
    short: "Well",
    type: "mana",
    cd: 28,
    mana: 0,
    restore: 120,
    effects: { impact: 0x66ccff, ring: 0x55bbff, hand: 0x66ccff, shake: 0.2 },
  },

  // Buffs — damage, haste, fortify
  {
    id: "overload_buff",
    name: "Overload",
    short: "Buff",
    type: "buff",
    cd: 20,
    mana: 30,
    buffMult: 1.4,
    buffDuration: 8,
    speedMult: 1.35,
    effects: { impact: 0xffd86a, ring: 0xffef85, hand: 0xffd86a, shake: 0.22 },
  },
  {
    id: "surge_of_haste",
    name: "Surge of Haste",
    short: "Haste",
    type: "buff",
    cd: 22,
    mana: 32,
    buffMult: 1.15,
    buffDuration: 7,
    speedMult: 1.25,
    atkSpeedMult: 1.6,
    effects: { impact: 0xfff07a, ring: 0xffe16a, hand: 0xffe16a, shake: 0.24 },
  },
  {
    id: "fortify",
    name: "Fortify",
    short: "Fort",
    type: "buff",
    cd: 26,
    mana: 28,
    buffMult: 1.1,
    buffDuration: 8,
    defensePct: 0.35,
    effects: { impact: 0x88ffd0, ring: 0x66ffc2, hand: 0x88ffd0, shake: 0.18 },
  },

  // Shields — defensive archetype
  {
    id: "storm_barrier",
    name: "Storm Barrier",
    short: "Barrier",
    type: "shield",
    cd: 18,
    mana: 28,
    duration: 6,
    shieldPct: 0.45,
    invulnDuration: 0.25,
    effects: { impact: 0x88ffd0, ring: 0x66ffc2, hand: 0x66ffc2, shake: 0.22 },
  },
  {
    id: "tempest_guard",
    name: "Tempest Guard",
    short: "Guard",
    type: "shield",
    cd: 26,
    mana: 34,
    duration: 5,
    shieldPct: 0.6,
    invulnDuration: 0.5,
    effects: { impact: 0xffe085, ring: 0xffcf6a, hand: 0xffe085, shake: 0.28 },
  },

  // Mobility
  {
    id: "lightning_dash",
    name: "Lightning Dash",
    short: "Dash",
    type: "dash",
    cd: 7,
    mana: 16,
    distance: 14,
    effects: { impact: 0x9fd8ff, ring: 0x9fd8ff, hand: 0x9fd8ff, shake: 0.12 },
  },
  {
    id: "blink_strike",
    name: "Blink Strike",
    short: "Blink",
    type: "blink",
    cd: 12,
    mana: 24,
    range: 24,
    effects: { impact: 0xbfe9ff, ring: 0xbfe9ff, hand: 0xbfe9ff, shake: 0.14 },
  },

  // Companion/clone
  {
    id: "thunder_image",
    name: "Thunder Image",
    short: "Clone",
    type: "clone",
    cd: 22,
    mana: 40,
    duration: 7,
    rate: 0.5,
    radius: 26,
    dmg: 18,
    effects: { impact: 0x9fd8ff, ring: 0x9fd8ff, hand: 0x9fd8ff, shake: 0.2 },
  },

  // Big-impact long cooldowns — nukes/supers
  {
    id: "zeus_judgement",
    name: "Zeus' Judgement",
    short: "Judg",
    type: "nova",
    cd: 42,
    mana: 80,
    radius: 28,
    dmg: 165,
    effects: { ring: 0xffe085, impact: 0xffc14d, hand: 0xffd86a, shake: 0.9 },
  },
  {
    id: "maelstrom",
    name: "Maelstrom",
    short: "Mael",
    type: "storm",
    cd: 40,
    mana: 72,
    radius: 34,
    strikes: 36,
    dmg: 22,
    duration: 9,
    effects: { ring: 0xa0e0ff, impact: 0x80d0ff, hand: 0x88ccff, shake: 0.7 },
  },
];

/**
 * Default loadout mapping stays close to the original Q/W/E/R
 */
export const DEFAULT_LOADOUT = ["chain_lightning", "lightning_bolt", "static_field", "thunderstorm"];
